### ISSUE TITLE
Output not highlighted when it  is selected first in the data mapper

### ISSUE THREAD

**Issue by poorna2152** [wso2/mi-vscode#284]
**Description:**
When a field in the output is selected first than in the output side, it is highlighted in a different way.
The following gif first shows the behaviour when the input side is selected first. The dot next to input field is coloured in blue when selected. But when a field in output side is selected first the dot next to the output is not coloured.
Usually the output field is selected first when there a function expression is needed to be added.
![issue3](https://github.com/user-attachments/assets/25207dfb-9d83-462c-a82e-e05940b2baaf)

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by madushajg** [comment]
This is the intended behaviour. The rationale behind this is that selecting a port for mapping and selecting a port for expression editing are two different actions, and the different highlighting is meant to indicate that distinction.

1. When you select an input port or an output port for mapping (by clicking on the fields), the port is fully highlighted to show the active connection.
2. When you focus on an output port to add or edit an expression, only the border is highlighted. This indicates that the port is in expression editing mode rather than mapping mode.

This differentiation in highlighting helps users understand the context of their selection and ensures clarity in their actions.
