### ISSUE TITLE
Improve Endpoint Creation Form

### ISSUE THREAD

**Issue by rosensilva** [wso2/mi-vscode#287]
**Description:**
<img width="1329" alt="Screenshot 2024-07-31 at 21 18 35" src="https://github.com/user-attachments/assets/72bb45e9-2a60-4b76-9b0c-f9b5ee0f72fd">

Out of these endpoints, 90% of the use cases are HTTP endpoints. We need to think of a way to hide the endpoint types that are not widely used. Also is it possible to merge these endpoints with connector endpoints? (salesforce connector, email connector connection, etc?)

**Affected Product Version:**
1.0.1

**Comment by ChinthakaJ98** [comment]
Until the new connector approach is introduced to the extension, we are only displaying the endpoint types that are commonly used. The rest of the endpoint types are hidden in a collapse so that the user can view them only if they require any other endpoint type.

<img width="730" alt="Screenshot 2024-10-03 at 10 11 51" src="https://github.com/user-attachments/assets/bf3e27cf-a586-4c31-9823-5e0465c680c9">
