### ISSUE TITLE
Cannot create a proxy service using WSDL file

### ISSUE THREAD

**Issue by DinithiDiaz** [wso2/mi-vscode#75]
**Description:**
There is no option to generate a proxy service using a WSDL file.

<img width="1512" alt="create-a-proxy" src="https://github.com/wso2/mi-vscode/assets/33226735/ba2065f0-308f-4767-8e57-2e83a68c677c">

---

**MI for VS Code Extension Version:** v0.9.24062409 (pre-release) 

---

**Doc Issues:** https://github.com/wso2/docs-mi/issues/412

**Comment by ChinthakaJ98** [comment]
When migrating the proxy service creation wizard from the Integration Studio to the MI extension it was decided to only support creation of a custom proxy and the other types to be supported via the diagram view after creating a proxy in order to allow them to be edited based on the user requirement. Therefore this issue cannot be addressed as we do not have a separate WSDL based proxy creation option now in the MI extension.
