### ISSUE TITLE
Respond mediator is not listed when clicking the add button inside the switch case

### ISSUE THREAD

**Issue by kalaiyarasiganeshalingam** [wso2/mi-vscode#80]
**Description:**
<img width="680" alt="Screenshot 2024-07-10 at 13 50 55" src="https://github.com/wso2/mi-vscode/assets/12771261/1e853662-9ca1-477b-939a-553a53f90718">

**Comment by gigara** [comment]
@rosensilva @thuva9872 Isn't it the expected behaviour?

**Comment by thuva9872** [comment]
No. 
`[Send, Respond, Loopback, Drop]` these mediators should not be allowed in `[Iterate, Foreach]`. In other cases it should be allowed. 
The issue here is related to not allowing `Respond` mediator in between two mediators as it can be only in the end. The condition that is used to check whether we are adding a new mediator between two mediators is not correct. We need to fix that.

**Comment by thuva9872** [comment]
Related Issue: https://github.com/wso2/mi-vscode/issues/7

**Comment by isudana** [comment]
Can we close this? anything pending?
